version: "3.9"

services:
  doc-processor:
    build: .
    container_name: doc-processor
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8008 --reload"
